### ISSUE TITLE
Regarding Errors with Shapes Dataset

### ISSUE THREAD

**Issue by mohitsharma29** [umd-huang-lab/transfer-fairness#1]
Hey
The code is throwing many errors when run for the Shapes dataset. Is it possible, by any chance to upload the working code for the Shapes dataset that was used to report the results in the paper?

Thank You

**Comment by bangann** [comment]
Hi,

Thank you for pointing it out! We'll fix it and let you know soon.

**Comment by bangann** [comment]
Hi Mohit,

We've updated our code. Could you try it again? For the Shapes dataset, instead of using .h5, we first save every image to a .jpg with the name to be its index. We do this because we found it would save loading time while training compared with reading from h5. Here's the snippet we use (Not very efficient though. It would take hours):
```
import h5py
from PIL import Image
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--start', type=int)
parser.add_argument('--end', type=int)
args = parser.parse_args()

_DATA_PATH = 'data/3dshape/3dshapes.h5'
dataset = h5py.File(_DATA_PATH, 'r')
data_path = 'data/shapes/images'


def main(args):
    for i in range(args.start, args.end):
        image = dataset['images'][i]
        img = Image.fromarray(image)
        img.save(data_path + '/' + str(i) + '.jpg')


if __name__ == "__main__":
    main(args)
```

**Comment by mohitsharma29** [comment]
Thank you for the above script. How did you set the start and the end index in the above script? Saving the images of the whole dataset will take quite some time (>2 days).

**Comment by bangann** [comment]
Hi Mohit,

Yes, saving the images will take a lot of time, so we use multiple CPUs. The start and end indices are set to make each CPU do part of the job. The minimum index is 0 and the maximum index is 480000 since there are 480000 images in total.
