### ISSUE TITLE
Regarding Initial Epochs with NewAdult dataset

### ISSUE THREAD

**Issue by mohitsharma29** [umd-huang-lab/transfer-fairness#2]
Hey

When running the code for the New Adult dataset, for the first 30 epochs or so, the loss and accuracy metrics stay flat before changing towards an expected curve. Since the paper does not provide the learning curves for the New Adult dataset, I wanted to confirm whether this is a dataset-specific problem or if this should not happen?
![image](https://github.com/umd-huang-lab/transfer-fairness/assets/15522704/3107cdcb-fc04-4ce7-848d-cddbeba5dad8)

**Comment by bangann** [comment]
Hi Mohit,

Could you please try the updated code and see if you still have such an observation?

**Comment by mohitsharma29** [comment]
Yes, the new code fixed this issue. Thank you.
May I ask what was causing this, and how were you guys able to fix it?

**Comment by bangann** [comment]
Hi Mohit,

We didn't have such an observation before. I don't know, but our previous code does have some problems since we merged two different versions of code from two members. Sorry about that. We are glad it works now!
